# Generated by Django 4.2.1 on 2023-08-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('you', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
