# Generated by Django 4.2.1 on 2023-08-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('you', '0002_category_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='longdecription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
